dist: trusty
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - cppcheck
    - docbook-xml
    - docbook-xsl
    - elinks
    - gperf
    - libxml2-utils
    - xsltproc
install:
- python -m pip install --user docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- cppcheck --error-exitcode=1 *.c
- private/autogen
- ./configure --prefix ~/.local || cat config.log /fail
- make -B
- xmllint --nonet --noout --valid doc/*.xml
- private/check-rst
- make install
- cd /
- pwnsjp; [ $? -eq 1 ]
- MANPATH=~/.local/share/man MANWIDTH=80 man 1 pwnsjp | grep -A 15 -w PWNSJP

# vim:ts=2 sts=2 sw=2 et
