language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - elinks
    - gperf
    - libxml2-utils
    - python-docutils
before_script:
- private/autogen
script:
- ./configure
- make -B
- xmllint --noout --valid doc/*.xml
- grep -r -l ft=rst doc/ | xargs -t -L1 -I{} rst2xml --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
