dist: trusty
sudo: false
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - docbook-xml
    - docbook-xsl
    - elinks
    - gperf
    - libxml2-utils
    - python-docutils
    - xsltproc
before_script:
- private/autogen
script:
- ./configure
- make -B
- xmllint --nonet --noout --valid doc/*.xml
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
