language: c
compiler:
- gcc
- clang
before_install:
- sudo apt-get update
- sudo apt-get install -y automake autoconf autoconf-archive elinks gperf
before_script:
- private/autogen
script:
- ./configure
- make -B

# vim:ts=2 sts=2 sw=2 et
