dist: trusty
sudo: false
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - docbook-xml
    - docbook-xsl
    - elinks
    - gperf
    - libxml2-utils
    - python-docutils
    - xsltproc
script:
- private/autogen
- ./configure --prefix ~/.local
- make -B
- xmllint --nonet --noout --valid doc/*.xml
- private/check-rst
- make install
- cd /
- pwnsjp; [ $? -eq 1 ]
- MANPATH=~/.local/share/man MANWIDTH=80 man 1 pwnsjp | grep -A 15 -w PWNSJP

# vim:ts=2 sts=2 sw=2 et
