config.o: config.c config.h common.h terminfo.h
html.o: html.c common.h html.h hue.h terminfo.h unicode.h
hue.o: hue.c common.h hue.h terminfo.h
io.o: io.c common.h memory.h io.h byteorder.h config.h unicode.h
main.o: main.c common.h memory.h byteorder.h config.h html.h hue.h io.h \
  regex.h terminfo.h ui.h unicode.h
memory.o: memory.c common.h memory.h
regex.o: regex.c common.h config.h memory.h regex.h
terminfo.o: terminfo.c common.h memory.h terminfo.h
ui.o: ui.c common.h ui.h io.h html.h hue.h terminfo.h unicode.h
unicode.o: unicode.c common.h memory.h unicode.h cmap-cp1250.h \
  cmap-iso8859-16.h cmap-iso8859-2.h cmap-usascii.h entity-hash.h \
  entity.h config.h
