autogen_header = data/autogen-header.inc.h

autohfiles = $(wildcard cmap-*.h) $(wildcard entity*.h)

.PHONY: headers
headers: $(autohfiles)

$(autohfiles): $(autogen_header)

cmap-cp1250.h: data/cmap-cp1250.gz tools/cmap-decode
	cat $(autogen_header) > $(@)~
	zcat $(<) | tools/cmap-decode cp1250 >> $(@)~
	mv -f $(@)~ $(@)

cmap-iso8859-2.h: data/cmap-iso8859-2.gz tools/cmap-iso8859-n.h.in tools/cmap-decode
	cat $(autogen_header) > $(@)~
	zcat $(<) | tools/cmap-iso8859-n.h.in 2 >> $(@)~
	zcat $(<) | tools/cmap-decode iso8859_2 >> $(@)~
	mv -f $(@)~ $(@)

cmap-iso8859-13.h: data/cmap-iso8859-13.gz tools/cmap-iso8859-n.h.in
	cat $(autogen_header) > $(@)~
	zcat $(<) | tools/cmap-iso8859-n.h.in 13 >> $(@)~
	mv -f $(@)~ $(@)

cmap-iso8859-16.h: data/cmap-iso8859-16.gz tools/cmap-iso8859-n.h.in
	cat $(autogen_header) > $(@)~
	zcat $(<) | tools/cmap-iso8859-n.h.in 16 >> $(@)~
	mv -f $(@)~ $(@)

cmap-usascii.h: tools/cmap-usascii.h.in
	cat $(autogen_header) > $(@)~
	tools/cmap-usascii.h.in >> $(@)~
	mv -f $(@)~ $(@)

entity.h: data/entities.dat tools/entity.h.in
	cat $(autogen_header) > $(@)~
	tools/entity.h.in < $(<) >> $(@)~
	mv -f $(@)~ $(@)

entity-hash.h: data/entities.dat tools/entity-hash.h.in
	tools/entity-hash.h.in < ${<} > $(@)~
	mv -f $(@)~ $(@)


.PHONY: clean-headers
clean-headers:
	rm -f $(autohfiles)

# vim:ts=4
