#!/bin/sh
name=pwnsjp
url=http://bitbucket.org/jwilk/pwnsjp
if [ $# -ne 1 ]
then
  printf "%s <version>\n" "$0" >&2
  exit 1
fi
set -e -x
pwd="$PWD"
version="$1"
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS="--owner root --group root --mode a+rX"
export GZIP="-9 -n"
mkdir -p "$sourceroot/$name-$version"
if [ -d .hg ]
then
    hg archive -r "$version" "$sourceroot/$name-$version"
else
    hg clone -r "$version" "$url" "$sourceroot/$name-$version"
fi
cd "$sourceroot"/*
private/autogen
make -f Makefile.hdr headers
rm -rf .hg*
rm -rf *.cache
cd ..
tar -czf "$pwd/$name-$version.tar.gz" */
rm -rf "$sourceroot"

# vim:ts=4 sw=4 et
