#!/usr/bin/perl

# Copyright © 2006, 2012 Jakub Wilk <jwilk@jwilk.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

use strict;
use warnings;

my ($charset) = @ARGV;
my $CHARSET = uc $charset;

print <<EOF
#include <wchar.h>
#ifndef CMAP_DECODE_${CHARSET}_H
#define CMAP_DECODE_${CHARSET}_H

static const wchar_t ${charset}[0x80] = L"\\
EOF
;

my %s;
$s{$_} = '\0' foreach (0x80 .. 0xff);

while (<STDIN>)
{
  next unless m'^<U([0-9A-F]{4})> */(x[0-9a-f]{2}).*';
  my $cp = hex $2;
  $s{$cp} = '\u' . lc($1);
  my $value = hex $1;
  $s{$cp} = '?' if $value >= 0x80 and $value < 0xA0;
}
print $s{$_} foreach (0x80 .. 0xff);
print <<EOF
\\
";

#endif
EOF
;

# vim:ts=2 sts=2 sw=2 et ft=perl
