#!/usr/bin/perl

# Copyright © 2012 Jakub Wilk <jwilk@jwilk.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

use v5.10;
use strict;
use warnings;

use autodie qw(open close);

sub process($)
{
    my ($line) = @_;
    return if $line eq '';
    my ($pre, $post) = $line =~ /(.+):(.*)/ or die;
    my @post = split ' ', $post;
    my @result = ();
    for (@post) {
        push @result, "$pre: $_";
    }
    for (sort @result) {
        print "$_\n";
    }
}

my $cc = $ENV{'CC'} // 'gcc';

open STDIN, '-|', $cc, '-MM', glob('*.c');
open STDOUT, '>', 'Makefile.dep';
my $line = '';
while (<STDIN>) {
    my $break = 0;
    chomp;
    if (s/\\$//) {
        $break = 1;
    }
    $line = "$line$_";
    next if $break;
    process($line);
    $line = '';
}
process($line);
close STDIN;
close STDOUT;

# vim:ts=4 sts=4 sw=4 et
